---

- hosts: all
  become: true
  tasks:


  - name: update repository index
    apt:
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: install apache2
    apt:
      name: apache2
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: add php support for apache
    apt:
      name: libapache2-mod-php
      state: latest
    when:  ansible_distribution == "Ubuntu"

  - name: update repository index
    yum:
      update_cache: yes
    when: ansible_distribution == "RedHat"

  - name: install apache2
    yum:
      name: httpd  
      state: latest
    when: ansible_distribution == "Redhat"

  - name: add php support for apache
    yum:
      name: php
      state: latest
    when:  ansible_distribution == "RedHat"
